### ISSUE TITLE
Wekan app container fails (it seems permissions) 

### ISSUE THREAD

**Issue by neooleg** [wekan/wekan-dev#1]
Following manual finished without errors, but Wekan not start and console shows the following:

```
/home/wekan/.meteor/packages/meteor-tool/.1.3.5_1.1sksnpz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: EACCES, mkdir '/home/wekan/app/.meteor/local'
```

**Comment by xet7** [comment]
@neooleg 

Is this related to this Wekan development environment, or https://github.com/wekan/wekan/issues/928 ?

**Comment by neooleg** [comment]
@xet7 

I had the same error reported as you caught [here](https://github.com/wekan/wekan/issues/928#issuecomment-289864168), but error code is _EACCES_ (and I have enough disk space).

Thus, probably this is not related issue or even this is my mistake.

**Comment by xet7** [comment]
@neooleg 

With "Wekan app container" do you mean Docker? It's currently broken, and fixing is in progress.

**Comment by neooleg** [comment]
Now I see
