### ISSUE TITLE
Installation fails: Unknown package in top-level dependencies for wekan-ldap, accounts-cas, wekan-scrollbar

### ISSUE THREAD

**Issue by Jacobclaerhout** [wekan/wekan-dev#11]
However I try to initialize the dev version of Wekan (using Root installation or via Docker), I come to the following error:

```
=> Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies: wekan:wekan-ldap
unknown package in top-level dependencies: wekan:accounts-cas
unknown package in top-level dependencies: wekan-scrollbar

ERROR: Service 'wekan-dev' failed to build: The command '/bin/sh -c chown -R wekan:wekan /home/wekan &&     chmod g+s /home/wekan &&     gosu wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build &&     chown wekan:wekan --recursive .meteor' returned a non-zero code: 1

```

**Comment by andresmanelli** [comment]
This should be fixed now

**Comment by WebrangerC** [comment]
2019-03-15: I just downloaded the .zip file, extracted and followed the directions. I am seeing this same error. Has the fix mentioned above propagated to the .zip file?

**Comment by xet7** [comment]
@WebrangerC 

What .zip file? Where did you download it from?

**Comment by WebrangerC** [comment]
Thank you for responding.
I clicked the download link on https://github.com/wekan/wekan on 3/15 and downloaded the .zip. Extracted and ran the rebuild-wekan.sh. Running on Kubuntu 18.04.2.  Have meteor v1.8.0.2 on system. Meteor in the wekan-devel directory shows 1.6.0.1

**Comment by xet7** [comment]
@WebrangerC 

Yes, rebuild-wekan.sh has option 1 to install these dependencies.
https://github.com/wekan/wekan/blob/devel/rebuild-wekan.sh#L116-L121

**Comment by WebrangerC** [comment]
I am not seeing the output from line 111, < echo "Building Wekan." >
Looking in detail, the last output I see is the meteor install to my home directory after which I get a command prompt. I do not have a 'packages' directory after execution. I can post the screen output if it adds value.  My BASH experience is limited but the 'break' in line 108 seems suspicious. How does that work if there is no associated LOOP?

**Comment by xet7** [comment]
@WebrangerC 

Huh? rebuild-wekan.sh is first run with 1 and then 2.

**Comment by andresmanelli** [comment]
@WebrangerC  Could you try building your image?

Follow the README from this repo, but before `./run.sh`, do `./build.sh`.

Let me know how that goes

**Comment by WebrangerC** [comment]
I had been running the rebuild-wekan.sh option 1 then option 2 on the .zip version. I took a look at the README.md file in the top level directory and didn't find a reference to the ./run.

SO, I went back and cloned the project, ran the rebuild-wekan with options 1 then 2 and successfully ran the system. The output from the 1st pass on the cloned directory looks like the output from the 1st pass on the .zip directory. The 2nd pass is much longer, doesn't end with the error.

I am up and running but would look into the zip file issue if I get some guidance.

**Comment by KrunalDholakiya** [comment]
I'm too facing the same issue while starting wekan locally in my Windows OS. Please help me with this. Below is the error.

Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies: wekan:wekan-ldap
unknown package in top-level dependencies: wekan:accounts-cas
unknown package in top-level dependencies: wekan-accounts-oidc
unknown package in top-level dependencies: wekan-scrollbar

**Comment by xet7** [comment]
For Windows:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

For Linux:
```
git clone https://github.com/wekan/wekan
cd wekan
./rebuild-wekan.sh   # Select 1
./rebuild-wekan.sh   # Select 2
./run-wekan.sh 
```
For just installing and using at Linux with Snap:
https://github.com/wekan/wekan-snap/wiki/Install

Or use docker:
``` 
git clone https://github.com/wekan/wekan
cd wekan
# optional: edit settings at docker-compose.yml
docker-compose up -d
```
