### ISSUE TITLE
run.sh gives error: ERROR: Service 'wekan-dev' failed to build

### ISSUE THREAD

**Issue by nerminator** [wekan/wekan-dev#12]
I am using Ubuntu 18.04.2 LTS inside a VirtualBox.
I have installed docker and docker-compose and successfully run hello-world docker app.
But when I try to execute ./run.sh, I am getting the following build error:

**ERROR**: Service 'wekan-dev' failed to build: The command '/bin/sh -c set -o xtrace &&     groupadd -g ${WEKAN_GID} wekan &&     useradd --system -m -u ${WEKAN_UID} -g ${WEKAN_GID} wekan &&     mkdir -p /home/wekan/app/.meteor &&         apt-get update -y && apt-get install -y --no-install-recommends ${BUILD_DEPS} &&         cp $(which tar) $(which tar)~ &&     ln -sf $(which bsdtar) $(which tar) &&         wget https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     wget https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt.asc &&     grep ${NODE_VERSION}-${ARCHITECTURE}.tar.gz SHASUMS256.txt.asc | shasum -a 256 -c - &&     rm -f SHASUMS256.txt.asc &&         tar xvzf node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     rm node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz &&     mv node-${NODE_VERSION}-${ARCHITECTURE} /opt/nodejs &&     ln -s /opt/nodejs/bin/node /usr/bin/node &&     ln -s /opt/nodejs/bin/npm /usr/bin/npm &&         npm install -g npm@${NPM_VERSION} &&     npm install -g node-gyp &&     npm install -g fibers@${FIBERS_VERSION}' returned a non-zero code: 100

**Comment by xet7** [comment]
I don't maintain this wekan-dev, some other Wekan contributors do, and I don't use this wekan-dev, but just commenting anyway.

When I usually build docker version from source, I do the following:
```
git clone https://github.com/wekan/wekan
cd wekan
```
Then I edit docker-compose.yml to uncomment these lines:
https://github.com/wekan/wekan/blob/devel/docker-compose.yml#L132-L142
And then:
```
docker-compose up -d --build
```
This makes Wekan run at http://localhost as shown here, using Docker Linux containers on Windows:

<img src="https://wekan.github.io/wekan-linux64bit-docker-in-win10.png" width="100%" alt="Docker Wekan on Windows" />

But if you update Docker for Windows, sometimes updates change to using Docker Windows containers, so Wekan does not start, and if switching back to Docker Linux containers does not work, then Docker needs to be reinstalled.

If you find some Wekan wiki pages outdated, please edit and fix those directly, wiki is community maintained and editable to all logged in GitHub users.

**Comment by xet7** [comment]
Sure Docker on Ubuntu VM also works with above.

**Comment by nerminator** [comment]
This worked ! 
I've tried the followings before:
 **1.   Windows build** 
        steps:  https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows
        result : FAILED
                   build from source on windows using cmd admin mode and dockers windows. This failed with 
_"Error: EPERM: operation not permitted, stat" error._

 **2.  Ubuntu Virtual box (Oracle)  (running on Windows)**
        steps:  https://github.com/wekan/wekan-dev 
        result:  FAILED
        error:   ERROR: Service 'wekan-dev' failed to build: The command '/bin/sh -c set -o xtrace && groupadd -g ${WEKAN_GID} wekan &..._

**3. Ubuntu app (from MS Store) on Windows 10** 
        steps:  https://github.com/wekan/wekan-dev 
        result:  FAILED
        error:   _ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?_
                    Executing run.sh command somehow terminates the docker service. 

**4. Windows Powershell in admin mode.**
     steps:   steps given here by @xet7 
     result: **SUCCESS!**

**Comment by xet7** [comment]
@nerminator 

Thanks, I have updated wiki:
https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows

1) Source on Windows version of Meteor/Node does not work.

2) Wekan-dev is broken. Using source rebuild-wekan.sh or docker install using https://github.com/wekan/wekan does work on Ubuntu VirtualBox VM. There is also old VirtualBox VM Wekan-Sandstorm.ova with Debian and all source/Snap/Docker versions installed at https://github.com/wekan/wekan/wiki/virtual-appliance , it can be updated to newest version using normal Linux apt-get update commands and source build scripts inside VM.

3) [Linux source install](https://github.com/wekan/wekan-dev/issues/12#issuecomment-468657290) on Ubuntu app does work, but Docker/Snap does not work on Ubuntu on Windows Subsystem for Linux.

4) Yes.

Thanks!

**Comment by JerryMWeeks** [comment]
Just tried on Windows 10 using PowerShell in admin mode, it fails at this:
+ cd /home/wekan/app
+ gosu wekan:wekan mkdir -p ./public/api
mkdir: cannot create directory './public/api': Permission denied
+ cd /home/wekan/app
+ gosu wekan:wekan /home/wekan/.meteor/meteor add standard-minifier-js
error: exec: "/home/wekan/.meteor/meteor": stat /home/wekan/.meteor/meteor: no such file or directory
ERROR: Service 'wekan' failed to build: The command '/bin/sh -c set -o xtrace &&     useradd --user-group --system --home-dir /home/wekan wekan &&         apt-get update -y && apt-get install -y --no-install-recommends ${BUILD_DEPS} &&     pip3 install -U pip setuptools wheel && … etc etc.

**Comment by xet7** [comment]
@JerryMWeeks 

Moved to https://github.com/wekan/wekan/issues/2533
