### ISSUE TITLE
No specific version for fibers cause make error

### ISSUE THREAD

**Issue by jameswangcnln78** [wekan/wekan-dev#2]
I got error like below when "npm install -g fibers &&"

>  (node) child_process: options.customFds option is deprecated. Use options.stdio instead.
> make: Entering directory /root/node_modules/fibers/build' CXX(target) Release/obj.target/fibers/src/fibers.o In file included from /root/.node-gyp/4.2.3/src/node.h:42, from ../src/coroutine.h:1, from ../src/fibers.cc:1: /root/.node-gyp/4.2.3/deps/v8/include/v8.h:336: error: expected unqualified-id before 'using' /root/.node-gyp/4.2.3/deps/v8/include/v8.h: In constructor 

The make error got gone when I specified the version like

> npm install -g fibers@1.0.5 && 

I wish this can help others.

**Comment by xet7** [comment]
Using fibers@1.0.15 is already documented at:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-and-build-wekan
and
https://github.com/wekan/wekan/blob/devel/Dockerfile

Is there some wiki page or elsewhere that fibers version number is not mentioned?

**Comment by jameswangcnln78** [comment]
I cloned https://github.com/wekan/wekan-dev.git and there is no specific version for fibers in Dockerfile.
What's the difference between wekan/wekan and wekan/wekan-dev?

**Comment by xet7** [comment]
@jameswangcnln78 

wekan-dev is docker development environment that is not up-to-date.

I develop wekan on wekan/wekan installed from source.

**Comment by jameswangcnln78** [comment]
Thanks for your relply!@xet7
