### ISSUE TITLE
Environment variables warning

### ISSUE THREAD

**Issue by jeanabraham** [wekan/wekan-dev#3]
Hi, 

I was able to complete the steps listed in the README. When I start wekan, I am getting the below warnings. Can I ignore them as they are set in the Dockerfile?

> jean:src$docker-compose start
> WARNING: The NODE_VERSION variable is not set. Defaulting to a blank string.
> WARNING: The METEOR_RELEASE variable is not set. Defaulting to a blank string.
> WARNING: The NPM_VERSION variable is not set. Defaulting to a blank string.
> WARNING: The ARCHITECTURE variable is not set. Defaulting to a blank string.
> WARNING: The SRC_PATH variable is not set. Defaulting to a blank string.
> WARNING: The METEOR_EDGE variable is not set. Defaulting to a blank string.
> WARNING: The USE_EDGE variable is not set. Defaulting to a blank string.
> Starting wekandb ... done
> Starting wekan ... done

Thanks!
Jean

**Comment by xet7** [comment]
@jeanabraham 

wekan-dev has not been updated for some time, it most likely uses old version of Wekan. You can look at current working Wekan's Dockerfile and add wekan-dev specific additions to it. If you get wekan-dev working, please submit pull request. Thanks!
https://github.com/wekan/wekan/blob/devel/Dockerfile

**Comment by jeanabraham** [comment]
Hi @xet7, I was able to have a local version running inspite of the warnings, without having to make any changes to what I cloned from wekan-dev.

**Comment by andresmanelli** [comment]
This should be fixed
